// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.
export const strings = {
    appName: "SandDance",
    bingsearch: "Bing",
    buttonSelectAll: "Select all",
    buttonData: "Data browser",
    buttonClose: "Close",
    buttonSelect: "Search & Select",
    buttonChartSettings: "Chart settings",
    buttonColorScheme: "Change color scheme",
    buttonColorSchemeMap: "Map color scheme to filtered data",
    buttonColorSchemeRemap: "Remap color to filtered data",
    buttonColorSchemeKeep: "Keep same color scheme",
    buttonCopyToClipboard: "Copy to clipboard",
    buttonExclude: "Exclude",
    buttonIsolate: "Isolate",
    buttonReset: "Stop filtering",
    buttonSearch: "Select by search",
    buttonSelectInverse: "Invert selection",
    buttonDeselect: "Clear selection",
    buttonToolbarFloat: "Float toolbar",
    buttonToolbarDock: "Dock toolbar",
    buttonToolbarHide: "Hide toolbar",
    buttonToolbarShow: "Show toolbar",
    buttonNextDataItem: "Next data item",
    buttonPrevDataItem: "Previous data item",
    buttonShowInDataBrowser: "Show in Data Browser",
    buttonCreateSnapshot: "Create snapshot",
    buttonAddExpression: "add expression",
    buttonAddExpressionGroup: "add group",
    buttonDeleteExpression: "delete",
    buttonDeleteExpressionGroup: "delete group",
    buttonDeleteSnapshot: "delete snapshot",
    buttonShowVegaSpec: "Show Vega spec",
    buttonLaunchVegaEditor: "Open Vega Editor",
    cameraHome: "Center chart in window",
    chartTypeScatterPlot: "Scatter plot",
    chartTypeDensity: "Density",
    chartTypeBarChart: "Bar chart",
    chartTypeTreeMap: "Tree map",
    chartTypeStacks: "Stacks",
    columnLabelColumn: "Column",
    columnLabelLink: "Web Search",
    columnLabelValue: "Value",
    dialogTitleChartSettings: "Chart settings",
    dialogTitleTools: "Tools",
    dialogTitleVegaSpec: "Vega specification",
    dialogTitleColor: "Chart color",
    dialogTitleDataBrowser: "Data browser",
    dialogTitleError: "Error",
    dialogTitleSnapshots: "Snapshots",
    dialogTitleSearch: "Select by search",
    groupLabelDataset: "Data rows",
    groupLabelChart: "Chart",
    groupLabelColumns: "Columns",
    groupLabelDataContent: "Selected rows",
    groupLabelFilter: "Filter",
    groupLabelSelection: "Select",
    labelChartAxes: "Axes",
    labelColumnMapping: "Column Mapping",
    labelChartType: "Chart type",
    labelChartTypeOptions: "Chart options",
    labelColorBin: "Color binning",
    labelColorBinExplanation: "For numeric columns",
    labelColorBinNone: "None (continuous)",
    labelColorBinQuantize: "Quantize",
    labelColorBinQuantile: "Quantile",
    labelColorFilter: "Note: Colors will be re-mapped to the filter when viewing this snapshot.",
    labelColorScheme: "Scheme",
    labelColumnColor: "Color by",
    labelColumnFacet: "Facet by",
    labelColumnSort: "Sort by",
    labelColumnX: "X Axis",
    labelColumnY: "Y Axis",
    labelColumnZ: "Z Axis",
    labelColumnSize: "Size by",
    labelColumnGroup: "Group by",
    labelDataset: "Dataset",
    labelDataItemIsFiltered: "Item is filtered from view",
    labelSearchClause: "Clause",
    labelSearchColumn: "Column",
    labelSearchOperator: "Operator",
    labelSearchValue: "Value",
    labelSnapshotDescription: "Description",
    labelTransitionDurations: "Transition durations",
    labelTransitionCamera: "2D / 3D view",
    labelTransitionColor: "Color",
    labelTransitionPosition: "Position",
    labelTransitionSize: "Size",
    labelVegaSpecData: "Data reference",
    labelVegaSpecNotes: "Note: You may need to change the color scheme to make this visible in Vega.",
    loading: "Loading...",
    tabLayout: "Layout",
    tabData: "Data",
    schemeCategorical: "Categorical",
    schemeDiverging: "Diverging",
    schemeDual: "Dual",
    schemeSequentialMultiHue: "Sequential Multi Hue",
    schemeSequentialSingleHue: "Sequential Single Hue",
    selectDataSpanAll: "All rows",
    selectDataSpanFilter: "Filtered",
    selectDataSpanSelection: "Selected",
    selectVegaSpecDataNone: "None",
    selectVegaSpecDataInline: "Inline - WARNING this may use substantial browser/clipboard memory for large data sets.",
    selectVegaSpecDataUrl: "URL",
    noContent: "none",
    record: (current, total) => `${current} of ${total}`,
    searchEQ: "=",
    searchNEQ: "<>",
    searchGT: ">",
    searchGTE: ">=",
    searchLT: "<",
    searchLTE: "<=",
    searchNULL: "is null or empty",
    searchIN: "contains",
    searchSW: "starts with",
    searchWHERE: "Where",
    searchAND: "and",
    searchOR: "or",
    selectAny: "-- any --",
    selectNone: "-- none --",
    selectNumeric: "Numeric",
    selectNumericWithBinning: "Numeric (with binning)",
    selectNonNumeric: "Categorical",
    tooltipSearch: (column, value) => `Click to search in '${column}' for "${value}"`,
    validateRequired: "required",
    viewType2d: "View in 2D",
    viewType3d: "View in 3D",
    nullAll: "Loading data...",
    nullFiltered: "You can filter by first making a selection, then choosing <b>Isolate</b> or <b>Exclude</b> in the top bar.",
    nullSelection: "You can select by: <ul><li>clicking the chart axes</li><li>clicking in the legend</li><li>searching</li</ul>",
    zeroAll: "Dataset contains zero rows.",
    zeroSearchResults: "No rows matched your search.",
    signalGroups: [
        { prefix: "Chart", label: "Chart options" },
        { prefix: "RoleColor", label: "Color options" },
        { prefix: "RoleFacet", label: "Facet options" },
        { prefix: "RoleSort", label: "Sort options" },
        { prefix: "RoleX", label: "X axis options" },
        { prefix: "RoleY", label: "Y axis options" },
        { prefix: "RoleZ", label: "Z axis options" },
        { prefix: "Text", label: "Text options" },
        { prefix: "*", label: "Options" }
    ]
};
